reverted back to stable alsa builds
alsa-lib v0.0.9 and alsa-utils v0.0.5

diff --git a/alsa-lib/utils/buildrpm b/alsa-lib/utils/buildrpm
--- a/alsa-lib/utils/buildrpm
+++ b/alsa-lib/utils/buildrpm
@@ -2,35 +2,24 @@
 
 source=.
 version=`cat $source/../version`
-package=$source/../../alsa-lib-$version.tar.bz2
-packagedir=/usr/src/redhat
-xrpmbuild=rpm
-rpmbuild --usage 2> /dev/null > /dev/null && xrpmbuild=rpmbuild
-
-if [ -d /usr/src/packages ]; then
-  packagedir=/usr/src/packages
-fi
-
-make -C .. clean
-make -C .. dist
+package=$source/../../alsa-lib-$version.tar.gz
 
 if [ ! -r $package ]; then
-  package=$source/../alsa-lib-$version.tar.bz2
-  if [ ! -r $package ]; then
-    echo "Error: wrong package: $package"
-    exit 1
-  fi
+  echo "Error: wrong package: $package"
+  exit 1
 fi
 
-cp -fv $package ${packagedir}/SOURCES
+make -C .. pack
+
+cp -fv $package /usr/src/redhat/SOURCES
 
 if [ ! -r $source/buildrpm ]; then
   echo "Error: invalid directory: $source"
   exit 1
 fi
 
-if [ ! -d ${packagedir} ]; then
-  echo "Error: ${packagedir} directory not found"
+if [ ! -d /usr/src/redhat ]; then
+  echo "Error: /usr/src/redhat directory not found"
   exit 1
 fi
 
@@ -40,7 +29,7 @@ if [ ! -r $source/alsa-lib.spec ]; then
   cd utils
 fi
 
-cp -fv $source/alsa-lib.spec ${packagedir}/SPECS
-cd ${packagedir}/SPECS
-$xrpmbuild -ba alsa-lib.spec
-cd ${packagedir}
+cp -fv $source/alsa-lib.spec /usr/src/redhat/SPECS
+cd /usr/src/redhat/SPECS
+rpm -ba alsa-lib.spec
+cd /usr/src/redhat
